name: Bug Report
description: Report a bug or issue with a configuration
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!
        
  - type: dropdown
    id: config-type
    attributes:
      label: Configuration Type
      description: What type of configuration is affected?
      options:
        - Device Configuration
        - Profile Configuration
        - Template
        - Schema
        - Other
    validations:
      required: true
      
  - type: input
    id: config-file
    attributes:
      label: Configuration File
      description: Which configuration file is affected?
      placeholder: e.g., configs/devices/example-dev-workstation.json
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug or issue
      placeholder: A clear description of what the bug is
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
    validations:
      required: false
